-- 在 Supabase Dashboard → SQL Editor → New query 中一次性运行本文件。
-- 说明：浏览器端只使用 publishable key；中奖逻辑在数据库函数里执行。

create extension if not exists pgcrypto;

create table if not exists public.visitors (
  id bigint generated by default as identity primary key,
  device_id uuid not null unique,
  first_seen_at timestamptz not null default now()
);

create table if not exists public.survey_responses (
  id bigint generated by default as identity primary key,
  device_id uuid not null unique references public.visitors(device_id) on delete cascade,
  answers jsonb not null,
  submitted_at timestamptz not null default now()
);

create table if not exists public.prizes (
  id bigint generated by default as identity primary key,
  name text not null,
  stock integer not null default 0 check (stock >= 0),
  weight numeric not null default 1 check (weight >= 0),
  enabled boolean not null default true,
  sort_order integer not null default 0
);

create table if not exists public.draw_logs (
  id bigint generated by default as identity primary key,
  device_id uuid not null unique references public.visitors(device_id) on delete cascade,
  prize_id bigint not null references public.prizes(id),
  created_at timestamptz not null default now()
);

create table if not exists public.shipping_orders (
  id bigint generated by default as identity primary key,
  device_id uuid not null unique references public.visitors(device_id) on delete cascade,
  prize_id bigint not null references public.prizes(id),
  receiver_name text not null,
  phone text not null,
  address text not null,
  status text not null default '待发货',
  created_at timestamptz not null default now()
);

alter table public.visitors enable row level security;
alter table public.survey_responses enable row level security;
alter table public.prizes enable row level security;
alter table public.draw_logs enable row level security;
alter table public.shipping_orders enable row level security;

-- 不给 anon 直接读写表；前端通过下方 RPC 调用。

create or replace function public.record_visit(p_device_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare n bigint;
begin
  insert into public.visitors(device_id) values (p_device_id) on conflict (device_id) do nothing;
  select count(*) into n from public.visitors;
  return jsonb_build_object('visitors',n);
end;
$$;

grant execute on function public.record_visit(uuid) to anon, authenticated;

create or replace function public.get_public_stats()
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'visitors',(select count(*) from public.visitors),
    'participants',(select count(*) from public.survey_responses),
    'draws',(select count(*) from public.draw_logs)
  );
$$;
grant execute on function public.get_public_stats() to anon, authenticated;

create or replace function public.submit_survey(p_device_id uuid, p_answers jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.visitors(device_id) values (p_device_id) on conflict (device_id) do nothing;
  if exists(select 1 from public.survey_responses where device_id=p_device_id) then
    raise exception '这台设备已经提交过问卷';
  end if;
  insert into public.survey_responses(device_id,answers) values(p_device_id,p_answers);
  return jsonb_build_object('ok',true);
end;
$$;
grant execute on function public.submit_survey(uuid,jsonb) to anon, authenticated;

create or replace function public.draw_prize(p_device_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  picked public.prizes;
  total_weight numeric;
  r numeric;
  running numeric := 0;
  x record;
  prize_names jsonb;
  wheel_index integer;
begin
  if not exists(select 1 from public.survey_responses where device_id=p_device_id) then
    raise exception '请先提交问卷';
  end if;
  if exists(select 1 from public.draw_logs where device_id=p_device_id) then
    select p.name into picked from public.draw_logs d join public.prizes p on p.id=d.prize_id where d.device_id=p_device_id;
    select coalesce(jsonb_agg(name order by sort_order,id),'[]'::jsonb) into prize_names from public.prizes where enabled=true;
    select coalesce(min(rn)-1,0) into wheel_index from (select id,row_number() over(order by sort_order,id) rn from public.prizes where enabled=true) q where id=picked.id;
    return jsonb_build_object('prize_name',picked.name,'wheel_index',wheel_index,'prize_names',prize_names,'is_thank_you',(lower(picked.name) like '%谢谢%'));
  end if;

  lock table public.prizes in row exclusive mode;
  select coalesce(sum(weight),0) into total_weight from public.prizes where enabled=true and stock>0;
  if total_weight <= 0 then raise exception '奖品库存已用完'; end if;
  r := random()*total_weight;
  for x in select * from public.prizes where enabled=true and stock>0 order by sort_order,id loop
    running := running + x.weight;
    if r <= running then picked := x; exit; end if;
  end loop;
  if picked.id is null then
    select * into picked from public.prizes where enabled=true and stock>0 order by sort_order,id limit 1;
  end if;
  update public.prizes set stock=stock-1 where id=picked.id;
  insert into public.draw_logs(device_id,prize_id) values(p_device_id,picked.id);
  select coalesce(jsonb_agg(name order by sort_order,id),'[]'::jsonb) into prize_names from public.prizes where enabled=true;
  select coalesce(min(rn)-1,0) into wheel_index from (select id,row_number() over(order by sort_order,id) rn from public.prizes where enabled=true) q where id=picked.id;
  return jsonb_build_object('prize_name',picked.name,'wheel_index',wheel_index,'prize_names',prize_names,'is_thank_you',(lower(picked.name) like '%谢谢%'));
end;
$$;
grant execute on function public.draw_prize(uuid) to anon, authenticated;

create or replace function public.save_shipping(p_device_id uuid,p_name text,p_phone text,p_address text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare pid bigint;
begin
  select prize_id into pid from public.draw_logs where device_id=p_device_id;
  if pid is null then raise exception '未找到中奖记录'; end if;
  insert into public.shipping_orders(device_id,prize_id,receiver_name,phone,address)
  values(p_device_id,pid,trim(p_name),trim(p_phone),trim(p_address))
  on conflict(device_id) do update set receiver_name=excluded.receiver_name,phone=excluded.phone,address=excluded.address;
  return jsonb_build_object('ok',true);
end;
$$;
grant execute on function public.save_shipping(uuid,text,text,text) to anon, authenticated;

-- 示例奖品。运行一次即可；重复运行会再加一份，请勿重复执行本段。
insert into public.prizes(name,stock,weight,enabled,sort_order) values
('定制帆布袋',100,20,true,1),
('精美中性笔',200,25,true,2),
('手机支架',80,15,true,3),
('校园笔记本',80,15,true,4),
('随机小礼品',100,10,true,5),
('谢谢参与',999999,15,true,6);
